FROM circleci/node:10

LABEL maintainer="Tomoya Honjo <tomoya.honjo22@gmail.com>"

RUN sudo apt-get install -y zip python python-dev python-pip
RUN sudo pip install --upgrade pip
RUN sudo pip install colorama==0.3.7 awscli awsebcli
